version: "3"

services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./Techeer-web-backend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./Techeer-web-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/test_db?serverTimezone=Asia/Seoul&charset=UTF-8&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    depends_on:
      - database

  database:
    build: ./mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test_db
